import 'package:flutter/services.dart';

/// Maps Flutter desktop keys to the Android key names accepted by STF.
///
/// STF's Socket.IO key payload is a string (for example `a`, `enter`, or
/// `switch_charset`). The STF device service resolves those names to Android
/// KeyCodes before injecting them, which is the same wire format used by the
/// Web console.
abstract final class AndroidKeyboardMapper {
  /// STF resolves this name to Android KEYCODE_SWITCH_CHARSET (95).
  static const String switchCharset = 'switch_charset';

  static String? keyNameFor(KeyEvent event) {
    return _physicalKeyNames[event.physicalKey] ??
        _logicalKeyNames[event.logicalKey];
  }

  static bool isCharsetSwitch(KeyEvent event) {
    final physicalKey = event.physicalKey;
    final logicalKey = event.logicalKey;
    return physicalKey == PhysicalKeyboardKey.convert ||
        physicalKey == PhysicalKeyboardKey.nonConvert ||
        physicalKey == PhysicalKeyboardKey.kanaMode ||
        physicalKey == PhysicalKeyboardKey.lang1 ||
        physicalKey == PhysicalKeyboardKey.lang2 ||
        logicalKey == LogicalKeyboardKey.alphanumeric ||
        logicalKey == LogicalKeyboardKey.convert ||
        logicalKey == LogicalKeyboardKey.nonConvert ||
        logicalKey == LogicalKeyboardKey.kanaMode ||
        logicalKey == LogicalKeyboardKey.kanjiMode ||
        logicalKey == LogicalKeyboardKey.lang1 ||
        logicalKey == LogicalKeyboardKey.lang2;
  }

  static final Map<PhysicalKeyboardKey, String> _physicalKeyNames = {
    PhysicalKeyboardKey.keyA: 'a',
    PhysicalKeyboardKey.keyB: 'b',
    PhysicalKeyboardKey.keyC: 'c',
    PhysicalKeyboardKey.keyD: 'd',
    PhysicalKeyboardKey.keyE: 'e',
    PhysicalKeyboardKey.keyF: 'f',
    PhysicalKeyboardKey.keyG: 'g',
    PhysicalKeyboardKey.keyH: 'h',
    PhysicalKeyboardKey.keyI: 'i',
    PhysicalKeyboardKey.keyJ: 'j',
    PhysicalKeyboardKey.keyK: 'k',
    PhysicalKeyboardKey.keyL: 'l',
    PhysicalKeyboardKey.keyM: 'm',
    PhysicalKeyboardKey.keyN: 'n',
    PhysicalKeyboardKey.keyO: 'o',
    PhysicalKeyboardKey.keyP: 'p',
    PhysicalKeyboardKey.keyQ: 'q',
    PhysicalKeyboardKey.keyR: 'r',
    PhysicalKeyboardKey.keyS: 's',
    PhysicalKeyboardKey.keyT: 't',
    PhysicalKeyboardKey.keyU: 'u',
    PhysicalKeyboardKey.keyV: 'v',
    PhysicalKeyboardKey.keyW: 'w',
    PhysicalKeyboardKey.keyX: 'x',
    PhysicalKeyboardKey.keyY: 'y',
    PhysicalKeyboardKey.keyZ: 'z',
    PhysicalKeyboardKey.digit1: '1',
    PhysicalKeyboardKey.digit2: '2',
    PhysicalKeyboardKey.digit3: '3',
    PhysicalKeyboardKey.digit4: '4',
    PhysicalKeyboardKey.digit5: '5',
    PhysicalKeyboardKey.digit6: '6',
    PhysicalKeyboardKey.digit7: '7',
    PhysicalKeyboardKey.digit8: '8',
    PhysicalKeyboardKey.digit9: '9',
    PhysicalKeyboardKey.digit0: '0',
    PhysicalKeyboardKey.enter: 'enter',
    PhysicalKeyboardKey.numpadEnter: 'numpad_enter',
    PhysicalKeyboardKey.escape: 'escape',
    PhysicalKeyboardKey.backspace: 'del',
    PhysicalKeyboardKey.tab: 'tab',
    PhysicalKeyboardKey.space: 'space',
    PhysicalKeyboardKey.minus: 'minus',
    PhysicalKeyboardKey.equal: 'equals',
    PhysicalKeyboardKey.bracketLeft: 'left_bracket',
    PhysicalKeyboardKey.bracketRight: 'right_bracket',
    PhysicalKeyboardKey.backslash: 'backslash',
    PhysicalKeyboardKey.semicolon: 'semicolon',
    PhysicalKeyboardKey.quote: 'apostrophe',
    PhysicalKeyboardKey.backquote: 'grave',
    PhysicalKeyboardKey.comma: 'comma',
    PhysicalKeyboardKey.period: 'period',
    PhysicalKeyboardKey.slash: 'slash',
    PhysicalKeyboardKey.capsLock: 'caps_lock',
    PhysicalKeyboardKey.numLock: 'num_lock',
    PhysicalKeyboardKey.scrollLock: 'scroll_lock',
    PhysicalKeyboardKey.arrowUp: 'dpad_up',
    PhysicalKeyboardKey.arrowDown: 'dpad_down',
    PhysicalKeyboardKey.arrowLeft: 'dpad_left',
    PhysicalKeyboardKey.arrowRight: 'dpad_right',
    PhysicalKeyboardKey.home: 'move_home',
    PhysicalKeyboardKey.end: 'move_end',
    PhysicalKeyboardKey.pageUp: 'page_up',
    PhysicalKeyboardKey.pageDown: 'page_down',
    PhysicalKeyboardKey.insert: 'insert',
    PhysicalKeyboardKey.f1: 'f1',
    PhysicalKeyboardKey.f2: 'f2',
    PhysicalKeyboardKey.f3: 'f3',
    PhysicalKeyboardKey.f4: 'f4',
    PhysicalKeyboardKey.f5: 'f5',
    PhysicalKeyboardKey.f6: 'f6',
    PhysicalKeyboardKey.f7: 'f7',
    PhysicalKeyboardKey.f8: 'f8',
    PhysicalKeyboardKey.f9: 'f9',
    PhysicalKeyboardKey.f10: 'f10',
    PhysicalKeyboardKey.f11: 'f11',
    PhysicalKeyboardKey.f12: 'f12',
    PhysicalKeyboardKey.delete: 'forward_del',
    PhysicalKeyboardKey.shiftLeft: 'shift_left',
    PhysicalKeyboardKey.shiftRight: 'shift_right',
    PhysicalKeyboardKey.controlLeft: 'ctrl_left',
    PhysicalKeyboardKey.controlRight: 'ctrl_right',
    PhysicalKeyboardKey.altLeft: 'alt_left',
    PhysicalKeyboardKey.altRight: 'alt_right',
    PhysicalKeyboardKey.metaLeft: 'meta_left',
    PhysicalKeyboardKey.metaRight: 'meta_right',
    PhysicalKeyboardKey.numpad0: 'numpad_0',
    PhysicalKeyboardKey.numpad1: 'numpad_1',
    PhysicalKeyboardKey.numpad2: 'numpad_2',
    PhysicalKeyboardKey.numpad3: 'numpad_3',
    PhysicalKeyboardKey.numpad4: 'numpad_4',
    PhysicalKeyboardKey.numpad5: 'numpad_5',
    PhysicalKeyboardKey.numpad6: 'numpad_6',
    PhysicalKeyboardKey.numpad7: 'numpad_7',
    PhysicalKeyboardKey.numpad8: 'numpad_8',
    PhysicalKeyboardKey.numpad9: 'numpad_9',
    PhysicalKeyboardKey.numpadDivide: 'numpad_divide',
    PhysicalKeyboardKey.numpadMultiply: 'numpad_multiply',
    PhysicalKeyboardKey.numpadSubtract: 'numpad_subtract',
    PhysicalKeyboardKey.numpadAdd: 'numpad_add',
    PhysicalKeyboardKey.numpadDecimal: 'numpad_dot',
    PhysicalKeyboardKey.numpadComma: 'numpad_comma',
    PhysicalKeyboardKey.numpadEqual: 'numpad_equals',
  };

  static final Map<LogicalKeyboardKey, String> _logicalKeyNames = {
    LogicalKeyboardKey.enter: 'enter',
    LogicalKeyboardKey.numpadEnter: 'numpad_enter',
    LogicalKeyboardKey.escape: 'escape',
    LogicalKeyboardKey.backspace: 'del',
    LogicalKeyboardKey.tab: 'tab',
    LogicalKeyboardKey.space: 'space',
    LogicalKeyboardKey.arrowUp: 'dpad_up',
    LogicalKeyboardKey.arrowDown: 'dpad_down',
    LogicalKeyboardKey.arrowLeft: 'dpad_left',
    LogicalKeyboardKey.arrowRight: 'dpad_right',
    LogicalKeyboardKey.home: 'move_home',
    LogicalKeyboardKey.end: 'move_end',
    LogicalKeyboardKey.pageUp: 'page_up',
    LogicalKeyboardKey.pageDown: 'page_down',
    LogicalKeyboardKey.insert: 'insert',
    LogicalKeyboardKey.f1: 'f1',
    LogicalKeyboardKey.f2: 'f2',
    LogicalKeyboardKey.f3: 'f3',
    LogicalKeyboardKey.f4: 'f4',
    LogicalKeyboardKey.f5: 'f5',
    LogicalKeyboardKey.f6: 'f6',
    LogicalKeyboardKey.f7: 'f7',
    LogicalKeyboardKey.f8: 'f8',
    LogicalKeyboardKey.f9: 'f9',
    LogicalKeyboardKey.f10: 'f10',
    LogicalKeyboardKey.f11: 'f11',
    LogicalKeyboardKey.f12: 'f12',
    LogicalKeyboardKey.delete: 'forward_del',
    LogicalKeyboardKey.shiftLeft: 'shift_left',
    LogicalKeyboardKey.shiftRight: 'shift_right',
    LogicalKeyboardKey.controlLeft: 'ctrl_left',
    LogicalKeyboardKey.controlRight: 'ctrl_right',
    LogicalKeyboardKey.altLeft: 'alt_left',
    LogicalKeyboardKey.altRight: 'alt_right',
    LogicalKeyboardKey.metaLeft: 'meta_left',
    LogicalKeyboardKey.metaRight: 'meta_right',
    LogicalKeyboardKey.capsLock: 'caps_lock',
    LogicalKeyboardKey.numLock: 'num_lock',
    LogicalKeyboardKey.scrollLock: 'scroll_lock',
    LogicalKeyboardKey.numpadComma: 'numpad_comma',
    LogicalKeyboardKey.numpadEqual: 'numpad_equals',
    LogicalKeyboardKey.keyA: 'a',
    LogicalKeyboardKey.keyB: 'b',
    LogicalKeyboardKey.keyC: 'c',
    LogicalKeyboardKey.keyD: 'd',
    LogicalKeyboardKey.keyE: 'e',
    LogicalKeyboardKey.keyF: 'f',
    LogicalKeyboardKey.keyG: 'g',
    LogicalKeyboardKey.keyH: 'h',
    LogicalKeyboardKey.keyI: 'i',
    LogicalKeyboardKey.keyJ: 'j',
    LogicalKeyboardKey.keyK: 'k',
    LogicalKeyboardKey.keyL: 'l',
    LogicalKeyboardKey.keyM: 'm',
    LogicalKeyboardKey.keyN: 'n',
    LogicalKeyboardKey.keyO: 'o',
    LogicalKeyboardKey.keyP: 'p',
    LogicalKeyboardKey.keyQ: 'q',
    LogicalKeyboardKey.keyR: 'r',
    LogicalKeyboardKey.keyS: 's',
    LogicalKeyboardKey.keyT: 't',
    LogicalKeyboardKey.keyU: 'u',
    LogicalKeyboardKey.keyV: 'v',
    LogicalKeyboardKey.keyW: 'w',
    LogicalKeyboardKey.keyX: 'x',
    LogicalKeyboardKey.keyY: 'y',
    LogicalKeyboardKey.keyZ: 'z',
    LogicalKeyboardKey.digit0: '0',
    LogicalKeyboardKey.digit1: '1',
    LogicalKeyboardKey.digit2: '2',
    LogicalKeyboardKey.digit3: '3',
    LogicalKeyboardKey.digit4: '4',
    LogicalKeyboardKey.digit5: '5',
    LogicalKeyboardKey.digit6: '6',
    LogicalKeyboardKey.digit7: '7',
    LogicalKeyboardKey.digit8: '8',
    LogicalKeyboardKey.digit9: '9',
  };
}
